# Site settings
title:          Nashmia Riaz
description:    "A blog for my technical endeavors"
baseurl:        "/Blog"
url:            "https://nashmia-riaz.github.io"

# Author
author:
  name:         Nashmia Riaz
  url:          https://github.com/nashmia-riaz
  email:        nashmia-riaz@hotmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - github-pages

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

remote_theme: chesterhow/tale
